// One-time dashboard credential generator: `npm run setup:auth`.
//
// Generates a strong random admin password and a random session secret, writes
// the bcrypt hash and the secret into .env.local, and writes the plaintext
// password into .env.local as a clearly-labelled comment.
//
// The plaintext is written to that one gitignored file and NOWHERE else — it is
// never printed to stdout, never logged by the running server, and never
// appears in the repo, the README, or the journal vault. That's the whole point
// of the comment line: it's the single place a human can go and read it.
import { randomBytes } from "node:crypto";
import { readFileSync, writeFileSync, existsSync, chmodSync } from "node:fs";
import bcrypt from "bcryptjs";

const ENV_PATH = ".env.local";
const BCRYPT_COST = 12;

// base64url so the password is safe to paste anywhere and safe to sit in a
// .env comment line: [A-Za-z0-9_-] only, no quoting or escaping needed.
function generatePassword(): string {
  return randomBytes(18).toString("base64url");
}

function generateSessionSecret(): string {
  return randomBytes(48).toString("hex");
}

export async function setupAuth(force: boolean): Promise<number> {
  if (!existsSync(ENV_PATH)) {
    console.error(`${ENV_PATH} does not exist. Create it first (see README).`);
    return 1;
  }

  const existing = readFileSync(ENV_PATH, "utf8");

  // Regenerating silently would lock the human out of a password they'd already
  // saved, and invalidate every live session. Make it an explicit choice.
  if (/^ADMIN_PASSWORD_HASH=/m.test(existing) && !force) {
    console.error(
      "Dashboard auth is already configured in .env.local.\n" +
        "The password is in that file as a comment near ADMIN_PASSWORD_HASH.\n" +
        "To generate a NEW password (invalidating the old one and all sessions):\n" +
        "  npm run setup:auth -- --force"
    );
    return 1;
  }

  const password = generatePassword();
  const hash = await bcrypt.hash(password, BCRYPT_COST);
  const secret = generateSessionSecret();

  // Drop any previous block so --force replaces rather than accumulates.
  const cleaned = existing
    .split("\n")
    .filter(
      (line) =>
        !/^ADMIN_PASSWORD_HASH=/.test(line) &&
        !/^SESSION_SECRET=/.test(line) &&
        !/^# dashboard login password/.test(line) &&
        !/^# --- Dashboard auth/.test(line)
    )
    .join("\n")
    .replace(/\n{3,}$/, "\n\n");

  // Single-quoted so the bcrypt hash's `$` characters can never be read as
  // interpolation by anything that sources this file; dotenv strips the quotes.
  const block =
    "\n# --- Dashboard auth (generated by `npm run setup:auth`) ---\n" +
    `# dashboard login password (save this somewhere safe, then feel free to delete this line): ${password}\n` +
    `ADMIN_PASSWORD_HASH='${hash}'\n` +
    `SESSION_SECRET='${secret}'\n`;

  writeFileSync(ENV_PATH, `${cleaned.replace(/\n+$/, "")}\n${block}`);
  // writeFileSync's `mode` option only applies when it creates the file, and
  // .env.local already exists — so tighten it explicitly. This file now holds a
  // plaintext password; other local users have no business reading it.
  chmodSync(ENV_PATH, 0o600);

  console.log(
    "Dashboard auth generated.\n" +
      `The password was written into ${ENV_PATH} as a comment line — open that\n` +
      "file to read it. It is deliberately not printed here, and it is not\n" +
      "stored anywhere else."
  );
  return 0;
}

if (require.main === module) {
  setupAuth(process.argv.includes("--force")).then((code) => {
    process.exitCode = code;
  });
}
